[app]
title = MyApp
package.name = com.myapp.android
package.domain = com.myapp
source.dir = .
source.main = main.py
version = 1.0.0
requirements = python3,kivy==2.2.1
android.sdk = 24
android.ndk = 23b
android.api = 33
android.minapi = 21
android.permissions = INTERNET
android.accept_sdk_license = True
log_level = 2
presplash.filename = %(source.dir)s/data/presplash.png
icon.filename = %(source.dir)s/data/icon.png
orientation = portrait
fullscreen = 0
